name: main

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"

jobs:
  test:
    name: "Testing"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup GO
        uses: actions/setup-go@v2-beta
      - name: Build
        run: go build cmd/sendtelegram/sendtelegram.go

