name: main

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"

jobs:
  test:
    name: "Testing"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        OS: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Setup GO
        uses: actions/setup-go@v2-beta
      - name: Build
        run: go build cmd/sendtelegram.go
      - name: Test
        run: ./cmd/sendtelegram -h
