name: main

on: push

jobs:
  test:
    name: "Testing"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup GO
        uses: actions/setup-go@v2-beta
      - name: Build
        run: go build cmd/sendtelegram/sendtelegram.go

  release:
    if: startsWith(github.event.ref, 'refs/tags')
    needs: [test]
    name: Create GitHub release
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Output Release URL File
        run: echo "${{ steps.create_release.outputs.upload_url }}" > release_url.txt
      - name: Save Release URL File for build
        uses: actions/upload-artifact@v1
        with:
          name: release_url
          path: release_url.txt

  build:
    if: startsWith(github.event.ref, 'refs/tags')
    name: Build software
    needs: [release]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ["linux", "darwin"]
        arch: ["amd64", "386"]

    steps:
      - uses: actions/checkout@v2
      - name: Load Release URL File from release job
        uses: actions/download-artifact@v1
        with:
          name: release_url
      - name: Get Release File Name & Upload URL
        id: get_release_info
        run: echo ::set-output name=upload_url::`cat release_url/release_url.txt`
      - name: Setup GO
        uses: actions/setup-go@v2-beta
      - name: Build sendtelegram
        run: GOOS=${{matrix.os}} GOARCH=${{matrix.arch}} go build -ldflags="-s -w" -o sendtelegram-${{matrix.arch}}-${{matrix.os}} cmd/sendtelegram/sendtelegram.go
      - name: "Adding build to release"
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release_info.outputs.upload_url }}
          asset_path: ./sendtelegram-${{matrix.arch}}-${{matrix.os}}
          asset_name: sendtelegram-${{matrix.arch}}-${{matrix.os}}
          asset_content_type: application/octet-stream

